version: 2

jobs:
  reap:
    working_directory: ~/repo
    docker:
      - image: condaforge/mambaforge:latest
    steps:
#       - checkout
      - run:
          name: checkout
          command: |
            git clone --depth 5 https://github.com/regro/libcfgraph.git --branch "$CIRCLE_BRANCH"
      - run:
          name: Update Conda
          command: |
            mamba update --all -y
            git clone --depth=1 https:///github.com/regro/libcflib
            pushd libcflib
            mamba install --file requirements/run.txt -y
            pip install --no-deps .
            popd
            rm -rf libcflib            
      - run:
          name: Run preloader
          command: |
            pushd libcfgraph
            python -m libcflib.preloader artifacts
            popd
          no_output_timeout: 60m
#       - run:
#           name: Run package harvester
#           command: |
#             python -m libcflib.harvest_pkgs
#           no_output_timeout: 60m

# DISABLED since the output format is too large
#       - run:
#           name: make import mapping
#           command: |
#             pushd libcfgraph
#             python -m libcflib.analyze_pkgs 75000
#             popd
      - run:
          name: list files
          command: |
            pushd libcfgraph
            python -c "import json; import glob; json.dump(glob.glob('artifacts/**/*.json', recursive=True), open('.file_listing.json', 'w'), indent=2)"
            popd
      - run:
          name: Report diff
          command: |
            pushd libcfgraph
            git diff .file_listing.json
            git add .
            popd
      - run:
          name: commit changes
          command: |
            pushd libcfgraph
            git config user.name circleci
            git config user.email circleci@libcfgraph.regro.github.com
            git diff-index --quiet HEAD || git commit -m "[ci skip] Updated graph"
            popd
      - run:
          name: push changes
          command: |
            pushd libcfgraph
            git pull
            git push https://${GH_PUSH_TOKEN}@github.com/regro/libcfgraph.git
            popd

workflows:
  version: 2
  commit:
    jobs:
      - reap
  hourly:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - reap
